aws_region     = "us-east-1"
instance_type  = "t2.micro"
key_pair_name  = "cloud9-key"
my_ip          = "3.236.221.105/32"
repo_clone_url = "https://github.com/ensarmesic/projekat1_web_app.git"
repo_name      = "projekat1_web_app"
